[hypervisor]
driver = "qemu"
script-path = "/etc/openvdc/scripts/"
image-server-uri = "http://10.0.100.12/images"
cache-path = "/var/cache/qemu/"

[zookeeper]
endpoint = "zk://10.0.100.10:2181,10.0.100.11:2181,10.0.100.12:2181/openvdc"

[bridges]
name = "br0"
type = "linux"

[executor-api]
# listen = "0.0.0.0:19372"
advertise-ip = "10.0.100.16"

[console]

  [console.ssh]
  # listen = ""
  advertise-ip = "10.0.100.16"
